// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbAreas
{
    public int are_ID { get; set; }

    public string are_Nombre { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime are_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? are_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? are_FechaEliminacion { get; set; }

    public bool? are_Estado { get; set; }

    public virtual ICollection<tbPersonal> tbPersonal { get; set; } = new List<tbPersonal>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}