// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbConsultasAcademicas
{
    public int coa_ID { get; set; }

    public int? est_ID { get; set; }

    public int? tic_ID { get; set; }

    public string coa_Descripcion { get; set; }

    public string coa_Recomendacion { get; set; }

    public bool? coa_Seguimiento { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime coa_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? coa_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? coa_FechaEliminacion { get; set; }

    public bool? coa_Estado { get; set; }

    public virtual tbEstudiantes est { get; set; }

    public virtual tbTipoConsulta tic { get; set; }

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}