// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbDiagnosticoOdonto
{
    public int trd_ID { get; set; }

    public int? sca_ID { get; set; }

    public int? tra_ID { get; set; }

    public string trd_Descripcion { get; set; }

    public string trd_Diagnostico { get; set; }

    public int trd_Duracion { get; set; }

    public decimal trd_Costo { get; set; }

    public bool? trd_Seguimiento { get; set; }

    public DateTime? trd_FechaSeg { get; set; }

    public string trd_Instrucciones { get; set; }

    public string trd_Observaciones { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime trd_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? trd_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? trd_FechaEliminacion { get; set; }

    public bool? trd_Estado { get; set; }

    public virtual tbSolicitudOdonAsignada sca { get; set; }

    public virtual tbTratamientos tra { get; set; }

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}