// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbDiagnosticosMedicos
{
    public int dia_ID { get; set; }

    public int? est_ID { get; set; }

    public string dia_DiagnosticoPrin { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime dia_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? dia_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? dia_FechaEliminacion { get; set; }

    public bool? dia_Estado { get; set; }

    public virtual tbEstudiantes est { get; set; }

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}