// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbEstudiantes
{
    public int est_ID { get; set; }

    public string est_NumeroCuenta { get; set; }

    public string est_NombreCompleto { get; set; }

    public string est_Correo { get; set; }

    public string est_Celular { get; set; }

    public string est_Carrera { get; set; }

    public bool est_EstadoM { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime est_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? est_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? est_FechaEliminacion { get; set; }

    public bool? est_Estado { get; set; }

    public virtual ICollection<tbConsultasAcademicas> tbConsultasAcademicas { get; set; } = new List<tbConsultasAcademicas>();

    public virtual ICollection<tbDiagnosticoOdonto> tbDiagnosticoOdonto { get; set; } = new List<tbDiagnosticoOdonto>();

    public virtual ICollection<tbDiagnosticosMedicos> tbDiagnosticosMedicos { get; set; } = new List<tbDiagnosticosMedicos>();

    public virtual ICollection<tbSolicitudApoyo> tbSolicitudApoyo { get; set; } = new List<tbSolicitudApoyo>();

    public virtual ICollection<tbSolicitudCitaOdon> tbSolicitudCitaOdon { get; set; } = new List<tbSolicitudCitaOdon>();

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}