// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbPantallas
{
    public int pan_ID { get; set; }

    public string pan_Nombre { get; set; }

    public string pan_URL { get; set; }

    public string pan_Identificador { get; set; }

    public string pan_Icono { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime pan_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? pan_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? pan_FechaEliminacion { get; set; }

    public bool? pan_Estado { get; set; }

    public virtual ICollection<tbRolesXPantallas> tbRolesXPantallas { get; set; } = new List<tbRolesXPantallas>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}