// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbPersonal
{
    public int per_ID { get; set; }

    public string per_Nombres { get; set; }

    public string per_Apellidos { get; set; }

    public string per_EstadoCivil { get; set; }

    public string per_Sexo { get; set; }

    public DateOnly per_FechaNac { get; set; }

    public string per_Telefono { get; set; }

    public string per_Direccion { get; set; }

    public string per_Correo { get; set; }

    public int? are_ID { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime per_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? per_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? per_FechaEliminacion { get; set; }

    public bool? per_Estado { get; set; }

    public virtual tbAreas are { get; set; }

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}