// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbPlanAccion
{
    public int pla_ID { get; set; }

    public string pla_ResumenSesion { get; set; }

    public string pla_Objetivo { get; set; }

    public string pla_ActividadSug { get; set; }

    public DateOnly? pla_FechaSeguimiento { get; set; }

    public string pla_Observacion { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime pla_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? pla_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? pla_FechaEliminacion { get; set; }

    public bool? pla_Estado { get; set; }

    public virtual ICollection<SolicitudesXPlanes> SolicitudesXPlanes { get; set; } = new List<SolicitudesXPlanes>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}