// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbRolesXPantallas
{
    public int rop_ID { get; set; }

    public int? rol_ID { get; set; }

    public int? pan_ID { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime rop_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? rop_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? rop_FechaEliminacion { get; set; }

    public bool? rop_Estado { get; set; }

    public virtual tbPantallas pan { get; set; }

    public virtual tbRoles rol { get; set; }

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}