// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbRoles
{
    public int rol_ID { get; set; }

    public string rol_Descripcion { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime rol_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? rol_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? rol_FechaEliminacion { get; set; }

    public bool? rol_Estado { get; set; }

    public virtual ICollection<tbRolesXPantallas> tbRolesXPantallas { get; set; } = new List<tbRolesXPantallas>();

    public virtual ICollection<tbUsuarios> tbUsuarios { get; set; } = new List<tbUsuarios>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}