// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbSolicitudOdonAsignada
{
    public int sca_ID { get; set; }

    public int? sco_ID { get; set; }

    public int? per_ID { get; set; }

    public bool? sca_Cancel { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime sca_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? sca_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? sca_FechaEliminacion { get; set; }

    public bool? sca_Estado { get; set; }

    public virtual tbPersonal per { get; set; }

    public virtual tbSolicitudCitaOdon sco { get; set; }

    public virtual ICollection<tbDiagnosticoOdonto> tbDiagnosticoOdonto { get; set; } = new List<tbDiagnosticoOdonto>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}