// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbSolicitudApoyo
{
    public int sol_ID { get; set; }

    public int? est_ID { get; set; }

    public string sol_MotivoConsulta { get; set; }

    public int? sol_MalestarEmocional { get; set; }

    public bool? sol_Asistencia { get; set; }

    public string sol_HorarioPref { get; set; }

    public bool? sol_Cancelacion { get; set; }

    public DateTime? sol_FechaCancelacion { get; set; }

    public DateTime sol_FechaCreacion { get; set; }

    public DateTime? sol_FechaModificacion { get; set; }

    public DateTime? sol_FechaEliminacion { get; set; }

    public bool? sol_Estado { get; set; }

    public bool? sol_Asignada { get; set; }

    public virtual tbEstudiantes est { get; set; }

    public virtual ICollection<tbSolicitudApoyoAsignada> tbSolicitudApoyoAsignada { get; set; } = new List<tbSolicitudApoyoAsignada>();

    public virtual ICollection<tbSolicitudesXPlanes> tbSolicitudesXPlanes { get; set; } = new List<tbSolicitudesXPlanes>();
}