// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbSolicitudApoyoAsignada
{
    public int spa_ID { get; set; }

    public int? sol_ID { get; set; }

    public int? per_ID { get; set; }

    public bool? spa_Cancel { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime spa_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? spa_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? spa_FechaEliminacion { get; set; }

    public bool? spa_Estado { get; set; }

    public virtual tbPersonal per { get; set; }

    public virtual tbSolicitudApoyo sol { get; set; }

    public virtual ICollection<tbSolicitudesXPlanes> tbSolicitudesXPlanes { get; set; } = new List<tbSolicitudesXPlanes>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}