// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbSolicitudesXPlanes
{
    public int spl_ID { get; set; }

    public int? sol_ID { get; set; }

    public int? pla_ID { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime spl_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? spl_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? spl_FechaEliminacion { get; set; }

    public bool? spl_Estado { get; set; }

    public virtual tbPlanAccion pla { get; set; }

    public virtual tbSolicitudApoyo sol { get; set; }

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}