// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbSolicitudCitaOdon
{
    public int sco_ID { get; set; }

    public int? est_ID { get; set; }

    public DateTime sco_FechaP { get; set; }

    public TimeSpan sco_Hora { get; set; }

    public string sco_Motivo { get; set; }

    public string sco_Prioridad { get; set; }

    public bool? sco_Cancelar { get; set; }

    public DateTime? sco_FechaCancelacion { get; set; }

    public DateTime sco_FechaCreacion { get; set; }

    public DateTime? sco_FechaModificacion { get; set; }

    public DateTime? sco_FechaEliminacion { get; set; }

    public bool? sco_Estado { get; set; }

    public virtual tbEstudiantes est { get; set; }

    public virtual ICollection<tbSolicitudOdonAsignada> tbSolicitudOdonAsignada { get; set; } = new List<tbSolicitudOdonAsignada>();
}