// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbSolicitudApoyo
{
    public int sol_ID { get; set; }

    public int? est_ID { get; set; }

    public string sol_ResumenSesion { get; set; }

    public string sol_MotivoConsulta { get; set; }

    public int? sol_MalestarEmocional { get; set; }

    public bool? sol_Asistencia { get; set; }

    public TimeOnly? sol_HorarioPref { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime sol_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? sol_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? sol_FechaEliminacion { get; set; }

    public bool? sol_Estado { get; set; }

    public virtual ICollection<SolicitudesXPlanes> SolicitudesXPlanes { get; set; } = new List<SolicitudesXPlanes>();

    public virtual tbEstudiantes est { get; set; }

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}