// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbTipoConsulta
{
    public int tic_ID { get; set; }

    public string tic_Descripcion { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime tic_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? tic_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? tic_FechaEliminacion { get; set; }

    public bool? tic_Estado { get; set; }

    public virtual ICollection<tbConsultasAcademicas> tbConsultasAcademicas { get; set; } = new List<tbConsultasAcademicas>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}