// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Models;

public partial class tbTratamientos
{
    public int tra_ID { get; set; }

    public string tra_Descripcion { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime tra_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? tra_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? tra_FechaEliminacion { get; set; }

    public bool? tra_Estado { get; set; }

    public virtual ICollection<tbDiagnosticoOdonto> tbDiagnosticoOdonto { get; set; } = new List<tbDiagnosticoOdonto>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}