// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SUDENEXT.Entities.Entities;

public partial class tbUsuarios
{
    public int usu_ID { get; set; }

    public string usu_Usuario { get; set; }

    public string usu_Contrasena { get; set; }

    public int? est_ID { get; set; }

    public int? per_ID { get; set; }

    public int? rol_ID { get; set; }

    public int usu_UsuarioCreacion { get; set; }

    public DateTime usu_FechaCreacion { get; set; }

    public int? usu_UsuarioModificacion { get; set; }

    public DateTime? usu_FechaModificacion { get; set; }

    public int? usu_UsuarioEliminacion { get; set; }

    public DateTime? usu_FechaEliminacion { get; set; }

    public bool? usu_Estado { get; set; }

    public virtual ICollection<tbUsuarios> Inverseusu_UsuarioCreacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual ICollection<tbUsuarios> Inverseusu_UsuarioEliminacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual ICollection<tbUsuarios> Inverseusu_UsuarioModificacionNavigation { get; set; } = new List<tbUsuarios>();

    public virtual tbEstudiantes est { get; set; }

    public virtual tbPersonal per { get; set; }

    public virtual tbRoles rol { get; set; }

    public virtual ICollection<tbAreas> tbAreasusu_UsuarioCreacionNavigation { get; set; } = new List<tbAreas>();

    public virtual ICollection<tbAreas> tbAreasusu_UsuarioEliminacionNavigation { get; set; } = new List<tbAreas>();

    public virtual ICollection<tbAreas> tbAreasusu_UsuarioModificacionNavigation { get; set; } = new List<tbAreas>();

    public virtual ICollection<tbConsultasAcademicas> tbConsultasAcademicasusu_UsuarioCreacionNavigation { get; set; } = new List<tbConsultasAcademicas>();

    public virtual ICollection<tbConsultasAcademicas> tbConsultasAcademicasusu_UsuarioEliminacionNavigation { get; set; } = new List<tbConsultasAcademicas>();

    public virtual ICollection<tbConsultasAcademicas> tbConsultasAcademicasusu_UsuarioModificacionNavigation { get; set; } = new List<tbConsultasAcademicas>();

    public virtual ICollection<tbDiagnosticoOdonto> tbDiagnosticoOdontousu_UsuarioCreacionNavigation { get; set; } = new List<tbDiagnosticoOdonto>();

    public virtual ICollection<tbDiagnosticoOdonto> tbDiagnosticoOdontousu_UsuarioEliminacionNavigation { get; set; } = new List<tbDiagnosticoOdonto>();

    public virtual ICollection<tbDiagnosticoOdonto> tbDiagnosticoOdontousu_UsuarioModificacionNavigation { get; set; } = new List<tbDiagnosticoOdonto>();

    public virtual ICollection<tbDiagnosticosMedicos> tbDiagnosticosMedicosusu_UsuarioCreacionNavigation { get; set; } = new List<tbDiagnosticosMedicos>();

    public virtual ICollection<tbDiagnosticosMedicos> tbDiagnosticosMedicosusu_UsuarioEliminacionNavigation { get; set; } = new List<tbDiagnosticosMedicos>();

    public virtual ICollection<tbDiagnosticosMedicos> tbDiagnosticosMedicosusu_UsuarioModificacionNavigation { get; set; } = new List<tbDiagnosticosMedicos>();

    public virtual ICollection<tbEstudiantes> tbEstudiantesusu_UsuarioCreacionNavigation { get; set; } = new List<tbEstudiantes>();

    public virtual ICollection<tbEstudiantes> tbEstudiantesusu_UsuarioEliminacionNavigation { get; set; } = new List<tbEstudiantes>();

    public virtual ICollection<tbEstudiantes> tbEstudiantesusu_UsuarioModificacionNavigation { get; set; } = new List<tbEstudiantes>();

    public virtual ICollection<tbPantallas> tbPantallasusu_UsuarioCreacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbPantallas> tbPantallasusu_UsuarioEliminacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbPantallas> tbPantallasusu_UsuarioModificacionNavigation { get; set; } = new List<tbPantallas>();

    public virtual ICollection<tbPersonal> tbPersonalusu_UsuarioCreacionNavigation { get; set; } = new List<tbPersonal>();

    public virtual ICollection<tbPersonal> tbPersonalusu_UsuarioEliminacionNavigation { get; set; } = new List<tbPersonal>();

    public virtual ICollection<tbPersonal> tbPersonalusu_UsuarioModificacionNavigation { get; set; } = new List<tbPersonal>();

    public virtual ICollection<tbPlanAccion> tbPlanAccionusu_UsuarioCreacionNavigation { get; set; } = new List<tbPlanAccion>();

    public virtual ICollection<tbPlanAccion> tbPlanAccionusu_UsuarioEliminacionNavigation { get; set; } = new List<tbPlanAccion>();

    public virtual ICollection<tbPlanAccion> tbPlanAccionusu_UsuarioModificacionNavigation { get; set; } = new List<tbPlanAccion>();

    public virtual ICollection<tbRolesXPantallas> tbRolesXPantallasusu_UsuarioCreacionNavigation { get; set; } = new List<tbRolesXPantallas>();

    public virtual ICollection<tbRolesXPantallas> tbRolesXPantallasusu_UsuarioEliminacionNavigation { get; set; } = new List<tbRolesXPantallas>();

    public virtual ICollection<tbRolesXPantallas> tbRolesXPantallasusu_UsuarioModificacionNavigation { get; set; } = new List<tbRolesXPantallas>();

    public virtual ICollection<tbRoles> tbRolesusu_UsuarioCreacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRoles> tbRolesusu_UsuarioEliminacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbRoles> tbRolesusu_UsuarioModificacionNavigation { get; set; } = new List<tbRoles>();

    public virtual ICollection<tbSolicitudApoyoAsignada> tbSolicitudApoyoAsignadausu_UsuarioCreacionNavigation { get; set; } = new List<tbSolicitudApoyoAsignada>();

    public virtual ICollection<tbSolicitudApoyoAsignada> tbSolicitudApoyoAsignadausu_UsuarioEliminacionNavigation { get; set; } = new List<tbSolicitudApoyoAsignada>();

    public virtual ICollection<tbSolicitudApoyoAsignada> tbSolicitudApoyoAsignadausu_UsuarioModificacionNavigation { get; set; } = new List<tbSolicitudApoyoAsignada>();

    public virtual ICollection<tbSolicitudApoyo> tbSolicitudApoyousu_UsuarioCreacionNavigation { get; set; } = new List<tbSolicitudApoyo>();

    public virtual ICollection<tbSolicitudApoyo> tbSolicitudApoyousu_UsuarioEliminacionNavigation { get; set; } = new List<tbSolicitudApoyo>();

    public virtual ICollection<tbSolicitudApoyo> tbSolicitudApoyousu_UsuarioModificacionNavigation { get; set; } = new List<tbSolicitudApoyo>();

    public virtual ICollection<tbSolicitudCitaOdon> tbSolicitudCitaOdonusu_UsuarioCreacionNavigation { get; set; } = new List<tbSolicitudCitaOdon>();

    public virtual ICollection<tbSolicitudCitaOdon> tbSolicitudCitaOdonusu_UsuarioEliminacionNavigation { get; set; } = new List<tbSolicitudCitaOdon>();

    public virtual ICollection<tbSolicitudCitaOdon> tbSolicitudCitaOdonusu_UsuarioModificacionNavigation { get; set; } = new List<tbSolicitudCitaOdon>();

    public virtual ICollection<tbSolicitudOdonAsignada> tbSolicitudOdonAsignadausu_UsuarioCreacionNavigation { get; set; } = new List<tbSolicitudOdonAsignada>();

    public virtual ICollection<tbSolicitudOdonAsignada> tbSolicitudOdonAsignadausu_UsuarioEliminacionNavigation { get; set; } = new List<tbSolicitudOdonAsignada>();

    public virtual ICollection<tbSolicitudOdonAsignada> tbSolicitudOdonAsignadausu_UsuarioModificacionNavigation { get; set; } = new List<tbSolicitudOdonAsignada>();

    public virtual ICollection<tbSolicitudesXPlanes> tbSolicitudesXPlanesusu_UsuarioCreacionNavigation { get; set; } = new List<tbSolicitudesXPlanes>();

    public virtual ICollection<tbSolicitudesXPlanes> tbSolicitudesXPlanesusu_UsuarioEliminacionNavigation { get; set; } = new List<tbSolicitudesXPlanes>();

    public virtual ICollection<tbSolicitudesXPlanes> tbSolicitudesXPlanesusu_UsuarioModificacionNavigation { get; set; } = new List<tbSolicitudesXPlanes>();

    public virtual ICollection<tbTipoConsulta> tbTipoConsultausu_UsuarioCreacionNavigation { get; set; } = new List<tbTipoConsulta>();

    public virtual ICollection<tbTipoConsulta> tbTipoConsultausu_UsuarioEliminacionNavigation { get; set; } = new List<tbTipoConsulta>();

    public virtual ICollection<tbTipoConsulta> tbTipoConsultausu_UsuarioModificacionNavigation { get; set; } = new List<tbTipoConsulta>();

    public virtual ICollection<tbTratamientos> tbTratamientosusu_UsuarioCreacionNavigation { get; set; } = new List<tbTratamientos>();

    public virtual ICollection<tbTratamientos> tbTratamientosusu_UsuarioEliminacionNavigation { get; set; } = new List<tbTratamientos>();

    public virtual ICollection<tbTratamientos> tbTratamientosusu_UsuarioModificacionNavigation { get; set; } = new List<tbTratamientos>();

    public virtual tbUsuarios usu_UsuarioCreacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioEliminacionNavigation { get; set; }

    public virtual tbUsuarios usu_UsuarioModificacionNavigation { get; set; }
}