// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using SUDENEXT.Entities.Entities;

namespace SUDENEXT.DataAccess.Context;

public partial class db_SUDENEXTContext : DbContext
{
    public db_SUDENEXTContext()
    {
    }

    public db_SUDENEXTContext(DbContextOptions<db_SUDENEXTContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tbAreas> tbAreas { get; set; }

    public virtual DbSet<tbConsultasAcademicas> tbConsultasAcademicas { get; set; }

    public virtual DbSet<tbDiagnosticoOdonto> tbDiagnosticoOdonto { get; set; }

    public virtual DbSet<tbDiagnosticosMedicos> tbDiagnosticosMedicos { get; set; }

    public virtual DbSet<tbEstudiantes> tbEstudiantes { get; set; }

    public virtual DbSet<tbPantallas> tbPantallas { get; set; }

    public virtual DbSet<tbPersonal> tbPersonal { get; set; }

    public virtual DbSet<tbPlanAccion> tbPlanAccion { get; set; }

    public virtual DbSet<tbRoles> tbRoles { get; set; }

    public virtual DbSet<tbRolesXPantallas> tbRolesXPantallas { get; set; }

    public virtual DbSet<tbSolicitudApoyo> tbSolicitudApoyo { get; set; }

    public virtual DbSet<tbSolicitudApoyoAsignada> tbSolicitudApoyoAsignada { get; set; }

    public virtual DbSet<tbSolicitudCitaOdon> tbSolicitudCitaOdon { get; set; }

    public virtual DbSet<tbSolicitudOdonAsignada> tbSolicitudOdonAsignada { get; set; }

    public virtual DbSet<tbSolicitudesXPlanes> tbSolicitudesXPlanes { get; set; }

    public virtual DbSet<tbTipoConsulta> tbTipoConsulta { get; set; }

    public virtual DbSet<tbTratamientos> tbTratamientos { get; set; }

    public virtual DbSet<tbUsuarios> tbUsuarios { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tbAreas>(entity =>
        {
            entity.HasKey(e => e.are_ID).HasName("PK_Gral_tbAreas_are_ID");

            entity.ToTable("tbAreas", "Gral");

            entity.HasIndex(e => e.are_Nombre, "UQ_Gral_tbAreas_are_Nombre").IsUnique();

            entity.Property(e => e.are_Estado).HasDefaultValue(true);
            entity.Property(e => e.are_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.are_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.are_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.are_Nombre)
                .IsRequired()
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbAreasusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbAreas_usu_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbAreasusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Gral_tbAreas_usu_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbAreasusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Gral_tbAreas_usu_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbConsultasAcademicas>(entity =>
        {
            entity.HasKey(e => e.coa_ID).HasName("PK_Acad_tbConsultasAcademicas_coa_ID");

            entity.ToTable("tbConsultasAcademicas", "Acad");

            entity.Property(e => e.coa_Descripcion).IsRequired();
            entity.Property(e => e.coa_Estado).HasDefaultValue(true);
            entity.Property(e => e.coa_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.coa_FechaEliminacion).HasColumnType("datetime");
            entity.Property(e => e.coa_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.coa_Recomendacion).HasMaxLength(255);
            entity.Property(e => e.coa_Seguimiento).HasDefaultValue(false);

            entity.HasOne(d => d.est).WithMany(p => p.tbConsultasAcademicas)
                .HasForeignKey(d => d.est_ID)
                .HasConstraintName("FK_Acad_tbConsultasAcademicas_est_ID_Gral_tbEstudiantes_est_ID");

            entity.HasOne(d => d.tic).WithMany(p => p.tbConsultasAcademicas)
                .HasForeignKey(d => d.tic_ID)
                .HasConstraintName("FK_Acad_tbConsultasAcademicas_tic_ID_Acad_tbTipoConsulta_tic_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbConsultasAcademicasusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acad_tbConsultasAcademicas_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbConsultasAcademicasusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Acad_tbConsultasAcademicas_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbConsultasAcademicasusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Acad_tbConsultasAcademicas_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbDiagnosticoOdonto>(entity =>
        {
            entity.HasKey(e => e.trd_ID).HasName("PK_Odon_tbTratamientoDiagnosticado_trd_ID");

            entity.ToTable("tbDiagnosticoOdonto", "Odon");

            entity.Property(e => e.trd_Costo).HasColumnType("decimal(10, 2)");
            entity.Property(e => e.trd_Descripcion).IsRequired();
            entity.Property(e => e.trd_Diagnostico)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.trd_Estado).HasDefaultValue(true);
            entity.Property(e => e.trd_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.trd_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.trd_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.trd_Instrucciones).HasMaxLength(255);
            entity.Property(e => e.trd_Observaciones).HasMaxLength(255);
            entity.Property(e => e.trd_Seguimiento).HasDefaultValue(false);
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.est).WithMany(p => p.tbDiagnosticoOdonto)
                .HasForeignKey(d => d.est_ID)
                .HasConstraintName("FK_Odon_tbTratamientoDiagnosticado_est_ID_Gral_tbEstudiantes_est_ID");

            entity.HasOne(d => d.tra).WithMany(p => p.tbDiagnosticoOdonto)
                .HasForeignKey(d => d.tra_ID)
                .HasConstraintName("FK_odon_tbTratamientoDiagnosticado_tra_ID_Odon_tbTratamientos_tra_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbDiagnosticoOdontousu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Odon_tbDiagnosticoOdonto_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbDiagnosticoOdontousu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Odon_tbDiagnosticoOdonto_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbDiagnosticoOdontousu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Odon_tbDiagnosticoOdonto_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbDiagnosticosMedicos>(entity =>
        {
            entity.HasKey(e => e.dia_ID).HasName("PK_Med_tbDiagnosticosMedicos_dia_ID");

            entity.ToTable("tbDiagnosticosMedicos", "Med");

            entity.Property(e => e.dia_DiagnosticoPrin).HasMaxLength(200);
            entity.Property(e => e.dia_Estado).HasDefaultValue(true);
            entity.Property(e => e.dia_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.dia_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.dia_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.est).WithMany(p => p.tbDiagnosticosMedicos)
                .HasForeignKey(d => d.est_ID)
                .HasConstraintName("FK_Med_tbDiagnosticosMedicos_est_ID_Gral_tbEstudiantes_est_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbDiagnosticosMedicosusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Med_tbDiagnosticosMedicos_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbDiagnosticosMedicosusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Med_tbDiagnosticosMedicos_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbDiagnosticosMedicosusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Med_tbDiagnosticosMedicos_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbEstudiantes>(entity =>
        {
            entity.HasKey(e => e.est_ID).HasName("PK_Gral_tbEstudiantes_est_ID");

            entity.ToTable("tbEstudiantes", "Gral");

            entity.HasIndex(e => e.est_NumeroCuenta, "UQ_Gral_tbEstudiantes_est_NumeroCuenta").IsUnique();

            entity.Property(e => e.est_Carrera)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.est_Celular)
                .IsRequired()
                .HasMaxLength(20)
                .IsUnicode(false);
            entity.Property(e => e.est_Contra)
                .IsRequired()
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.est_Correo)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.est_Estado).HasDefaultValue(true);
            entity.Property(e => e.est_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.est_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.est_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.est_NombreCompleto)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.est_NumeroCuenta)
                .IsRequired()
                .HasMaxLength(11)
                .IsUnicode(false);
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbEstudiantesusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbEstudiantes_usu_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbEstudiantesusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Gral_tbEstudiantes_usu_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbEstudiantesusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Gral_tbEstudiantes_usu_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbPantallas>(entity =>
        {
            entity.HasKey(e => e.pan_ID).HasName("PK_Acce_tbPantallas_pan_ID");

            entity.ToTable("tbPantallas", "Acce");

            entity.Property(e => e.pan_Estado).HasDefaultValue(true);
            entity.Property(e => e.pan_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.pan_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.pan_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.pan_Icono)
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.pan_Identificador)
                .HasMaxLength(5)
                .IsUnicode(false);
            entity.Property(e => e.pan_Nombre)
                .HasMaxLength(25)
                .IsUnicode(false);
            entity.Property(e => e.pan_URL).HasMaxLength(255);
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbPantallasusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbPantallas_usu_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbPantallasusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Acce_tbPantallas_usu_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbPantallasusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Acce_tbPantallas_usu_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbPersonal>(entity =>
        {
            entity.HasKey(e => e.per_ID).HasName("PK_Gral_tbPersonal_per_ID");

            entity.ToTable("tbPersonal", "Gral");

            entity.HasIndex(e => e.per_Correo, "UQ_Gral_tbPersonal_per_Correo").IsUnique();

            entity.HasIndex(e => e.per_Telefono, "UQ_Gral_tbPersonal_per_Telefono").IsUnique();

            entity.Property(e => e.per_Apellidos)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.per_Correo)
                .IsRequired()
                .HasMaxLength(80);
            entity.Property(e => e.per_Direccion)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.per_Estado).HasDefaultValue(true);
            entity.Property(e => e.per_EstadoCivil)
                .IsRequired()
                .HasMaxLength(2)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.per_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.per_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.per_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.per_Nombres)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.per_Sexo)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .IsFixedLength();
            entity.Property(e => e.per_Telefono)
                .IsRequired()
                .HasMaxLength(15)
                .IsUnicode(false);
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.are).WithMany(p => p.tbPersonal)
                .HasForeignKey(d => d.are_ID)
                .HasConstraintName("FK_Gral_tbPersonal_are_ID_Gral_tbAreas_are_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbPersonalusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Gral_tbPersonal_usu_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbPersonalusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Gral_tbPersonal_usu_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbPersonalusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Gral_tbPersonal_usu_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbPlanAccion>(entity =>
        {
            entity.HasKey(e => e.pla_ID).HasName("PK_Psi_tbPlanAccion_pla_ID");

            entity.ToTable("tbPlanAccion", "Psi");

            entity.Property(e => e.pla_ActividadSug)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.pla_Estado).HasDefaultValue(true);
            entity.Property(e => e.pla_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.pla_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.pla_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.pla_Objetivo)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.pla_Observacion)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.pla_ResumenSesion)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbPlanAccionusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Psi_tbPlanAccion_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbPlanAccionusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Psi_tbPlanAccion_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbPlanAccionusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Psi_tbPlanAccion_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbRoles>(entity =>
        {
            entity.HasKey(e => e.rol_ID).HasName("PK_Acce_tbRoles_rol_ID");

            entity.ToTable("tbRoles", "Acce");

            entity.HasIndex(e => e.rol_Descripcion, "UQ_Acce_tbRoles_rol_Descripcion").IsUnique();

            entity.Property(e => e.rol_Descripcion).HasMaxLength(30);
            entity.Property(e => e.rol_Estado).HasDefaultValue(true);
            entity.Property(e => e.rol_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.rol_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.rol_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbRolesusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbRoles_usu_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbRolesusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Acce_tbRoles_usu_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbRolesusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Acce_tbRoles_usu_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbRolesXPantallas>(entity =>
        {
            entity.HasKey(e => e.rop_ID).HasName("PK_Acce_tbRolesxPantallas_rop_ID");

            entity.ToTable("tbRolesXPantallas", "Acce");

            entity.Property(e => e.rop_Estado).HasDefaultValue(true);
            entity.Property(e => e.rop_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.rop_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.rop_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.pan).WithMany(p => p.tbRolesXPantallas)
                .HasForeignKey(d => d.pan_ID)
                .HasConstraintName("FK_Acce_tbRolesxPantallas_pan_ID_Acce_tbPantallas_pan_ID");

            entity.HasOne(d => d.rol).WithMany(p => p.tbRolesXPantallas)
                .HasForeignKey(d => d.rol_ID)
                .HasConstraintName("FK_Acce_tbRolesxPantallas_rol_ID_Acce_tbRoles_rol_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbRolesXPantallasusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbRolesXPantallas_usu_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbRolesXPantallasusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Acce_tbRolesXPantallas_usu_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbRolesXPantallasusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Acce_tbRolesXPantallas_usu_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbSolicitudApoyo>(entity =>
        {
            entity.HasKey(e => e.sol_ID).HasName("PK_Psi_tbSolicitudApoyo_sol_ID");

            entity.ToTable("tbSolicitudApoyo", "Psi");

            entity.Property(e => e.sol_Asignada).HasDefaultValue(false);
            entity.Property(e => e.sol_Asistencia).HasDefaultValue(false);
            entity.Property(e => e.sol_Cancelacion).HasDefaultValue(false);
            entity.Property(e => e.sol_Estado).HasDefaultValue(true);
            entity.Property(e => e.sol_FechaCancelacion).HasColumnType("datetime");
            entity.Property(e => e.sol_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.sol_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.sol_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.sol_MotivoConsulta)
                .IsRequired()
                .HasMaxLength(200);
            entity.Property(e => e.sol_ResumenSesion)
                .IsRequired()
                .HasMaxLength(200);

            entity.HasOne(d => d.est).WithMany(p => p.tbSolicitudApoyo)
                .HasForeignKey(d => d.est_ID)
                .HasConstraintName("FK_Psi_tbSolicitudApoyo_est_ID_Gral_tbEstudiantes_est_ID");
        });

        modelBuilder.Entity<tbSolicitudApoyoAsignada>(entity =>
        {
            entity.HasKey(e => e.spa_ID).HasName("PK_Psi_tbSolicitudApoyoAsignada_spa_ID");

            entity.ToTable("tbSolicitudApoyoAsignada", "Psi");

            entity.Property(e => e.spa_Cancel).HasDefaultValue(false);
            entity.Property(e => e.spa_Estado).HasDefaultValue(true);
            entity.Property(e => e.spa_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.spa_FechaEliminacion).HasColumnType("datetime");
            entity.Property(e => e.spa_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.per).WithMany(p => p.tbSolicitudApoyoAsignada)
                .HasForeignKey(d => d.per_ID)
                .HasConstraintName("FK_Psi_tbSolicitudApoyoAsignada_per_ID_Gral_tbPersonal_per_ID");

            entity.HasOne(d => d.sol).WithMany(p => p.tbSolicitudApoyoAsignada)
                .HasForeignKey(d => d.sol_ID)
                .HasConstraintName("FK_Psi_tbSolicitudApoyoAsignada_sco_ID_Psi_tbSolicitudApoyo_sol_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbSolicitudApoyoAsignadausu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Psi_tbSolicitudApoyoAsignada_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbSolicitudApoyoAsignadausu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Psi_tbSolicitudApoyoAsignada_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbSolicitudApoyoAsignadausu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Psi_tbSolicitudApoyoAsignada_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbSolicitudCitaOdon>(entity =>
        {
            entity.HasKey(e => e.sco_ID).HasName("PK_Odon_tbSolicitudCitaOdon_sco_ID");

            entity.ToTable("tbSolicitudCitaOdon", "Odon");

            entity.Property(e => e.sco_Asignada).HasDefaultValue(false);
            entity.Property(e => e.sco_Cancelar).HasDefaultValue(false);
            entity.Property(e => e.sco_Estado).HasDefaultValue(true);
            entity.Property(e => e.sco_FechaCancelacion).HasColumnType("datetime");
            entity.Property(e => e.sco_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.sco_FechaEliminacion).HasColumnType("datetime");
            entity.Property(e => e.sco_FechaModificacion).HasColumnType("datetime");
            entity.Property(e => e.sco_Motivo)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.sco_Prioridad)
                .IsRequired()
                .HasMaxLength(1)
                .IsUnicode(false)
                .HasDefaultValue("B")
                .IsFixedLength();

            entity.HasOne(d => d.est).WithMany(p => p.tbSolicitudCitaOdon)
                .HasForeignKey(d => d.est_ID)
                .HasConstraintName("FK_Odon_tbSolicitudCitaOdon_est_ID_Gral_tbEstudiantes_est_ID");
        });

        modelBuilder.Entity<tbSolicitudOdonAsignada>(entity =>
        {
            entity.HasKey(e => e.sca_ID).HasName("PK_Odon_tbSolicitudOdonAsignada_sca_ID");

            entity.ToTable("tbSolicitudOdonAsignada", "Odon");

            entity.Property(e => e.sca_Cancel).HasDefaultValue(false);
            entity.Property(e => e.sca_Estado).HasDefaultValue(true);
            entity.Property(e => e.sca_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.sca_FechaEliminacion).HasColumnType("datetime");
            entity.Property(e => e.sca_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.per).WithMany(p => p.tbSolicitudOdonAsignada)
                .HasForeignKey(d => d.per_ID)
                .HasConstraintName("FK_Odon_tbSolicitudOdonAsignada_per_ID_Gral_tbPersonal_per_ID");

            entity.HasOne(d => d.sco).WithMany(p => p.tbSolicitudOdonAsignada)
                .HasForeignKey(d => d.sco_ID)
                .HasConstraintName("FK_Odon_tbSolicitudOdonAsignada_sco_ID_Odon_tbSolicitudCitaOdon_sco_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbSolicitudOdonAsignadausu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Odon_tbSolicitudOdonAsignada_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbSolicitudOdonAsignadausu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Odon_tbSolicitudOdonAsignada_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbSolicitudOdonAsignadausu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Odon_tbSolicitudOdonAsignada_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbSolicitudesXPlanes>(entity =>
        {
            entity.HasKey(e => e.spl_ID).HasName("PK_Psi_SolicitudesXPlanes_spl_ID");

            entity.ToTable("tbSolicitudesXPlanes", "Psi");

            entity.Property(e => e.spl_Estado).HasDefaultValue(true);
            entity.Property(e => e.spl_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.spl_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.spl_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.pla).WithMany(p => p.tbSolicitudesXPlanes)
                .HasForeignKey(d => d.pla_ID)
                .HasConstraintName("FK_Psi_SolicitudesXPlanes_pla_ID_Psi_tbPlanAccion_pla_ID");

            entity.HasOne(d => d.sol).WithMany(p => p.tbSolicitudesXPlanes)
                .HasForeignKey(d => d.sol_ID)
                .HasConstraintName("FK_Psi_SolicitudesXPlanes_sol_ID_Psi_tbSolicitudApoyo_sol_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbSolicitudesXPlanesusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Psi_SolicitudesXPlanes_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbSolicitudesXPlanesusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Psi_SolicitudesXPlanes_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbSolicitudesXPlanesusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Psi_SolicitudesXPlanes_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbTipoConsulta>(entity =>
        {
            entity.HasKey(e => e.tic_ID).HasName("PK_Acad_tbTipoConsulta_tic_ID");

            entity.ToTable("tbTipoConsulta", "Acad");

            entity.Property(e => e.tic_Descripcion)
                .IsRequired()
                .HasMaxLength(80);
            entity.Property(e => e.tic_Estado).HasDefaultValue(true);
            entity.Property(e => e.tic_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.tic_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.tic_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbTipoConsultausu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acad_tbTipoConsulta_usu_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbTipoConsultausu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Acad_tbTipoConsulta_usu_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbTipoConsultausu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Acad_tbTipoConsulta_usu_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbTratamientos>(entity =>
        {
            entity.HasKey(e => e.tra_ID).HasName("PK_Odon_tbTratamientos_tra_ID");

            entity.ToTable("tbTratamientos", "Odon");

            entity.Property(e => e.tra_Descripcion)
                .IsRequired()
                .HasMaxLength(100);
            entity.Property(e => e.tra_Estado).HasDefaultValue(true);
            entity.Property(e => e.tra_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.tra_FechaEliminacion).HasColumnType("datetime");
            entity.Property(e => e.tra_FechaModificacion).HasColumnType("datetime");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.tbTratamientosusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Odon_tbTratamientos_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.tbTratamientosusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Odon_tbTratamientos_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.tbTratamientosusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Odon_tbTratamientos_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        modelBuilder.Entity<tbUsuarios>(entity =>
        {
            entity.HasKey(e => e.usu_ID).HasName("PK_Acce_tbUsuarios_usu_ID");

            entity.ToTable("tbUsuarios", "Acce");

            entity.Property(e => e.usu_Contrasena)
                .IsRequired()
                .HasMaxLength(255);
            entity.Property(e => e.usu_Estado).HasDefaultValue(true);
            entity.Property(e => e.usu_FechaCreacion).HasColumnType("datetime");
            entity.Property(e => e.usu_FechaEliminacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.usu_FechaModificacion)
                .HasDefaultValueSql("(NULL)")
                .HasColumnType("datetime");
            entity.Property(e => e.usu_Usuario)
                .IsRequired()
                .HasMaxLength(80);
            entity.Property(e => e.usu_UsuarioEliminacion).HasDefaultValueSql("(NULL)");
            entity.Property(e => e.usu_UsuarioModificacion).HasDefaultValueSql("(NULL)");

            entity.HasOne(d => d.per).WithMany(p => p.tbUsuarios)
                .HasForeignKey(d => d.per_ID)
                .HasConstraintName("FK_Acce_tbUsuarios_per_ID_Gral_tbPersonal_per_ID");

            entity.HasOne(d => d.rol).WithMany(p => p.tbUsuarios)
                .HasForeignKey(d => d.rol_ID)
                .HasConstraintName("FK_Acce_tbUsuarios_rol_ID_Acce_tbRoles_rol_ID");

            entity.HasOne(d => d.usu_UsuarioCreacionNavigation).WithMany(p => p.Inverseusu_UsuarioCreacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioCreacion)
                .OnDelete(DeleteBehavior.ClientSetNull)
                .HasConstraintName("FK_Acce_tbUsuarios_usu_UsuarioCreacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioEliminacionNavigation).WithMany(p => p.Inverseusu_UsuarioEliminacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioEliminacion)
                .HasConstraintName("FK_Acce_tbUsuarios_usu_UsuarioEliminacion_Acce_tbUsuarios_usu_ID");

            entity.HasOne(d => d.usu_UsuarioModificacionNavigation).WithMany(p => p.Inverseusu_UsuarioModificacionNavigation)
                .HasForeignKey(d => d.usu_UsuarioModificacion)
                .HasConstraintName("FK_Acce_tbUsuarios_usu_UsuarioModificacion_Acce_tbUsuarios_usu_ID");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}